name: Scalaz
baseurl: /scalaz
description: Scalaz examples
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: c420ee9e+20180523-2216-SNAPSHOT
org: org.scalaz
markdown: kramdown
