name: Scalaz
baseurl: /scalaz
description: Scalaz examples
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: e493de3e+20180618-1712-SNAPSHOT
org: org.scalaz
markdown: kramdown
