name: Scalaz
baseurl: /scalaz
description: Scalaz examples
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 2e2fffe6+20180522-2201-SNAPSHOT
org: org.scalaz
markdown: kramdown
