name: Scalaz
baseurl: /scalaz
description: Scalaz examples
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 8a499f75+20180523-0921-SNAPSHOT
org: org.scalaz
markdown: kramdown
