name: Scalaz
baseurl: /scalaz
description: Scalaz examples
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 8876b9a1+20180604-1915-SNAPSHOT
org: org.scalaz
markdown: kramdown
